### ISSUE TITLE
Finalize PyCon India 2021 Logo

### ISSUE THREAD

**Issue by RiteshAgrawal** [pythonindia/inpycon2021-tasks#14]
We have 5 logo option available for the conference and would like to have feedback for the same. 
Please use :thumbsup: for your preferred logo. Make sure to provide the feedback before March 10

**Comment by RiteshAgrawal** [comment]
Logo 2
![Uploading c2.jpg…]()

**Comment by RiteshAgrawal** [comment]
Logo 3
![Uploading c3.jpg…]()

**Comment by RiteshAgrawal** [comment]
Logo 4
![Uploading c4.jpg…]()

**Comment by RiteshAgrawal** [comment]
Logo 5
![Uploading c5.jpg…]()

**Comment by brilliantblu** [comment]
> Logo 4
> ![c4](https://user-images.githubusercontent.com/47899089/110001346-4d192200-7d3a-11eb-867c-c868c7098494.jpg)

Logo 4 looks chill, relax and stress-free!

**Comment by KanakKvdi** [comment]
I truly love no. **4 **and** 5!**

**Comment by KanakKvdi** [comment]
I think 4 gets my vote, considering the theme and our current living style or "normal". 4 conveys it eloquently!

**Comment by shivangdubey** [comment]
Logo 1 also seems nice, subtle colours with a very trending theme.

**Comment by ChiragSukhala** [comment]
> Logo 5
> ![c5](https://user-images.githubusercontent.com/47899089/110001387-5904e400-7d3a-11eb-8a53-35df82b30767.jpg)

5th one is cool and futuristic. It represents the knowledge accessibility we have today and python's contribution in it. Also motivates to attend online events as there is no geographic limitations now, and use tech to build a better world. 

my vote to 5th.

**Comment by rayandas** [comment]
We should close the Logo issue as we past the deadline today which was 20:00 IST. Logo 4 is the winner I can see. 🎉 @RiteshAgrawal

**Comment by RiteshAgrawal** [comment]
Based on the feedback and votes, logo4 has been finalised for PyCon India 2021.

Closing the issue
