### ISSUE TITLE
PyCon India 2021 | Call for Volunteers meeting

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2021-tasks#16]
Please leave a desired time you are available at for the meeting, I'll schedule the meeting accordingly. 

CC:
@sayanchowdhury @abhishekmishragithub

**Comment by abhishekmishragithub** [comment]
I am fine with Post lunch.

**Comment by realslimshanky** [comment]
@sayanchowdhury what about you?

**Comment by abhishekmishragithub** [comment]
@realslimshanky, finally we can close this issue 😅

**Comment by sayanchowdhury** [comment]
The meeting is done and concluded.
