### ISSUE TITLE
In-Kind sponsorships

### ISSUE THREAD

**Issue by GoelJatin** [pythonindia/inpycon2021-tasks#28]
Consider whether we want to have in-kind sponsors and what benefits we would offer. E.g.;

1. Logo on website
2. SM announcement
3. Mention in Opening address
4. Mention in Closing address (Optional)

**Comment by anistark** [comment]
Are we stuck somewhere on this? 

@inovizz @GoelJatin 

I can see the announcement issue #51

**Comment by GoelJatin** [comment]
Nope, we had created this towards the beginning to plan further on it and now we've other individual tasks already created for it, closing this one.
