### ISSUE TITLE
Create Pyflames event on each of the meetup group page

### ISSUE THREAD

**Issue by RiteshAgrawal** [pythonindia/inpycon2021-tasks#34]

**Comment by RiteshAgrawal** [comment]
Abhiram need to share the generic content to be posted on each meetup group.

**Comment by abhiramr** [comment]
In the content below, please remove your own Chapter name in the brackets and please add the rest of the chapter names. - @RiteshAgrawal - Can you please mention all the chapter names? 

<hr>

**Generic content -** 

Agenda:

Pycon 2021 is just a few months away. So as a precursor, we're conducting a couple of meetups collaborating with all the other chapters across the country as well! (Bangpypers, Python Pune, Pydelhi, ChennaiPy, HydPy, PyLadies, rest-to-be-added)
The event is called PyFlames 2021 and we've had a version of this last year as well. 

The first PyFlames 2021 event is to be conducted on May 2 2021 and we're accepting Talk proposals for the same!
The duration of the talk is intended to 20 minutes - 15 mins talk+ 5 mins Q&A and there are to be a total of 8 talks. 

Talks - TBD

Notes:

1. RSVP opens 7 days before the event.

2. The event is free of cost.

3. Waitlisted participants will receive confirmation notification about a day before the event.

4. If you aren't sure or have other important work to do, please UNRSVP and help others attend.
