### ISSUE TITLE
Create blog for Pyflames

### ISSUE THREAD

**Issue by RiteshAgrawal** [pythonindia/inpycon2021-tasks#36]

**Comment by RiteshAgrawal** [comment]
Two blogs
- One blog in general for the event
- Other blog about the speakers

**Comment by raukadah** [comment]
Can we post a single blog post including the schedule with speaker name in it?

**Comment by RiteshAgrawal** [comment]
@raukadah Yes, we will be doing the same

**Comment by RiteshAgrawal** [comment]
Blog published
