### ISSUE TITLE
Create poster for pyflames

### ISSUE THREAD

**Issue by RiteshAgrawal** [pythonindia/inpycon2021-tasks#37]

**Comment by RiteshAgrawal** [comment]
-  All meetup groups need to provide the logo

**Comment by akshaygin** [comment]
PythonPune logo image, download it from here: https://github.com/pythonpune/design/blob/master/logo/full-logo/PythonPune_logo_1000X1000_90dpi.png

**Comment by abhiramr** [comment]
Bangpypers - https://github.com/bangpypers/assets/blob/master/logo/bangpypers-square-large.png

**Comment by iamaravindsekar** [comment]
How many logos are we expecting? And would be great to know the deadline for closing this issue

**Comment by RiteshAgrawal** [comment]
@noblebatman 6 logos. 
Target would be wednesday EOD

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/115524048-5428cf00-a2ab-11eb-9b0f-5e6ceb40b00c.png)

**Comment by realslimshanky** [comment]
![PyDelhi Logo](https://github.com/pydelhi/pydelhi.github.io/raw/master/assets/images/android-icon-144x144.png)

**Comment by iamaravindsekar** [comment]
Hello there, done with the PyFlames poster and attaching it here, I have also added it to the Gdrive
url - https://drive.google.com/drive/u/0/folders/1GVsbjU16PltmZAUxhJS1e31BkAAKutfY
![PYflames](https://user-images.githubusercontent.com/20441340/115540613-d5885d80-a2bb-11eb-8fe4-a723a4570e42.png)

**Comment by manaswinidas** [comment]
![logoname](https://user-images.githubusercontent.com/22885912/115550833-efc83880-a2c7-11eb-93d7-ebcef2630e2f.jpeg)
![logoname-removebg-preview](https://user-images.githubusercontent.com/22885912/115550847-f191fc00-a2c7-11eb-87c6-f2fa897126ec.png)

**Comment by iamaravindsekar** [comment]
Attaching the updated poster, It can also be found in the Gdrive 
Url - https://drive.google.com/file/d/1vQTQA_Q7B_GLj0NeIL4LBa4B6Hf61oX_/view?usp=sharing
![PYflames](https://user-images.githubusercontent.com/20441340/115748126-845b9500-a3b3-11eb-8b3d-610afe311593.png)

**Comment by RiteshAgrawal** [comment]
Ritesh to take permission from PyJaipur to add their logo in the Pyflames.

**Comment by realslimshanky** [comment]
Event Scheduled on PyDelhi Meetup page thanks to Satyakaam - https://www.meetup.com/pydelhi/events/277708533/

**Comment by satyaakam** [comment]
![PYflames](https://user-images.githubusercontent.com/822770/116765713-2dedf680-aa44-11eb-9492-8559ac56d312.png)

**Comment by satyaakam** [comment]
pasting the updated image 

![PYflames](https://user-images.githubusercontent.com/822770/116765739-5970e100-aa44-11eb-9664-48f5178ec73e.png)

**Comment by iamaravindsekar** [comment]
@RiteshAgrawal Should the PyJaipur logo be added on the poster?

**Comment by RiteshAgrawal** [comment]
> @RiteshAgrawal Should the PyJaipur logo be added on the poster?

Yes Please. I will confirm with them also. Thanks for pointing it out.

**Comment by RiteshAgrawal** [comment]
Also please update the event name from "PyCon India Flames" to "PyFlames"

**Comment by RiteshAgrawal** [comment]
> > @RiteshAgrawal Should the PyJaipur logo be added on the poster?
> 
> Yes Please. I will confirm with them also. Thanks for pointing it out.

@noblebatman Since I am unable to reach PyJaipur people to take the permission to use logo, at this point we can go ahead without using PyJaipur logo

**Comment by shivankgtm** [comment]
> > > @RiteshAgrawal Should the PyJaipur logo be added on the poster?
> > 
> > 
> > Yes Please. I will confirm with them also. Thanks for pointing it out.
> 
> @noblebatman Since I am unable to reach PyJaipur people to take the permission to use logo, at this point we can go ahead without using PyJaipur logo

Hi we at PyJaipur were not awar of it, just got aware of it from @satyaakam on our TG. We at PyJaipur don't have much people we used to have 2-3 years back to run it in full phase. the first team of it is now quite distributed because of there job profiles in different states. we do believe we would be in more focus with time. 

here is the link to image resourses. feel free to use them.
https://github.com/PyJaipur/PyJaipur/tree/master/website/src/images

**Comment by RiteshAgrawal** [comment]
>Hi we at PyJaipur were not awar of it, just got aware of it from @satyaakam on our TG. We at PyJaipur don't have much people we used to have 2-3 years back to run it in full phase. the first team of it is now quite distributed because of there job profiles in different states. we do believe we would be in more focus with time.

Thanks @satyaakam for reaching them out. 
@Shivank98 Please reach out to us in case you require any help. 

>here is the link to image resourses. feel free to use them.
https://github.com/PyJaipur/PyJaipur/tree/master/website/src/images

@noblebatman Please add PyJaipur logo also in the poster.

**Comment by shivankgtm** [comment]
@RiteshAgrawal Thanks, I ll surely reach out :)

**Comment by iamaravindsekar** [comment]
Hey folks, I have made the changes to the poster, Its also available in the Gdrive Url - https://drive.google.com/file/d/1A_p-rehEJkxWc_742Mr-AJ6T1uGSko_3/view?usp=sharing

![PYflames](https://user-images.githubusercontent.com/20441340/116816214-a6f16900-ab7e-11eb-9da6-873e36173421.png)
