### ISSUE TITLE
Finalise speakers for Pyflames

### ISSUE THREAD

**Issue by RiteshAgrawal** [pythonindia/inpycon2021-tasks#39]

**Comment by RiteshAgrawal** [comment]
Bangpypers - Anand C - Joy of Programming

**Comment by Sc0rpi0n101** [comment]
PyDelhi - anjalibhavan - Ethical Considerations While Building AI Systems
https://github.com/pydelhi/talks/issues/193

**Comment by RiteshAgrawal** [comment]
Agenda:

10:30 - 10:40 - Intro to PyCon India 2021 and community chapters
10:40 - 11:00 - How to get started with Programming? - Hari Sapna Nair
11:00 - 11:20 - The File Server - Vipin Kumar
11:20 - 11:40 - Building web apps for ML/AI using Python StreamLit - Suman Debnath
11:40 - 12:00 - Onwards & Upwards with PYTHON - Subhashree Hazra
12:00 - 12:10 - BYOD(Drink)
12:10 - 12:30 - The Joy of Programming - Anand C
12:30 - 12:50 - Ethical Considerations While Building AI Systems - Anjali Bhavan 
12:50 - 1:10 - Build Serverless Python Applications using AWS Chalice - Harsh Bardhan Mishra
1:10 - 1:30 - Python and Flutter application for Colouring and Enhancing Old Photos - Utkarsh Mishra

PyCon India Office Hours (AMA regarding PyCon India 2021)
