### ISSUE TITLE
Guidelines for Outreach Partners [content request]

### ISSUE THREAD

**Issue by rachejazz** [pythonindia/inpycon2021-tasks#40]
We should prepare content that we would want our outreach partners to send out.
They may tweak it or put them on their own words but this will give them an idea on what to share. 

Should cover the following:
- [ ] mail for cfp, 
- [ ] tickets later, 
- [ ] fb post, twitter, LinkedIn, insta etc..

@Sc0rpi0n101 @rayandas @rachejazz 
For scrutiny: @anistark @abhishekmishragithub

**Comment by anistark** [comment]
@Sc0rpi0n101 @rachejazz 
Any update here?

**Comment by rachejazz** [comment]
@anistark yes, this is the blog:
https://in.pycon.org/blog/2021/outreach-partners.html. Closing this.
