### ISSUE TITLE
Update PyCon India mailing list description

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2021-tasks#43]
![Screenshot from 2021-04-17 23-01-32](https://user-images.githubusercontent.com/22801822/115121531-eb9ed100-9fd0-11eb-914d-78e3f330d25f.png)

The mailing list description needs an uplift and could also have a mention of twitter and instagram this time around. Assiging Chandan so he assigns someone else.

**Comment by satyaakam** [comment]
I have a made all the changes you can close this
