### ISSUE TITLE
[Deployment needed] PyCon India blog

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon2021-tasks#45]
Request the deployment of the blog. Thanks! @pythonindia/pycon-india-2021-leads-approvers @pythonindia/pycon-india-2020-infrastructure  cc: @Sc0rpi0n101

**Comment by vipulgupta2048** [comment]
Request the deployment of the blog. Thanks! @pythonindia/pycon-india-2021-leads-approvers @pythonindia/pycon-india-2020-infrastructure cc: @Sc0rpi0n101

We have another blog merged today for mentorship and their session is tomorrow. It would be really helpful if we can deploy the blog by EOD.

**Comment by anistark** [comment]
@vipulgupta2048 Can we close this or something pending here?
