### ISSUE TITLE
Announce Outreach Partners

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2021-tasks#49]
We can announce 1 per day in regular interval. So far, we got 2 only.

- [x]  Merge PR and deploy website. 
- [x]  Announce FOSS United. (social media channels only) - @rayandas 
- [x]  Announce GirlScript. (social media channels only) - @rayandas

**Comment by rayandas** [comment]
FOSS United: https://twitter.com/pyconindia/status/1392084010612924416
GirlScript: https://twitter.com/pyconindia/status/1392388284131680257

**Comment by rayandas** [comment]
Closing the issue.
