### ISSUE TITLE
PyCon India 2021 Website Bootstrap

### ISSUE THREAD

**Issue by palnabarun** [pythonindia/inpycon2021-tasks#5]
- [x] Create boilerplate @abhishekmishragithub
- [x] Create repo @palnabarun 
- [x] Deploy website at /2021 @palnabarun 
- [ ] Redirect / to /2021 @palnabarun (should be done before announcement)

**Comment by satyaakam** [comment]
When are we getting the new website design live ?

**Comment by anistark** [comment]
New design is also live now. Closing this.

**Comment by satyaakam** [comment]
i still see the old theme here https://in.pycon.org/blog/

**Comment by anistark** [comment]
@satyaakam blog has old theme. We're discussing on Zulip wg/technology about it.
