### ISSUE TITLE
Announce second keynote speaker

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon2021-tasks#54]
Info
Scheduled for June 2nd, 2021 at 6 PM.

Tasks

- [x]  Social Media announcement post @rayandas
- [x] Thumbnail design @noblebatman 
- [x]  Blog post announcement @Sc0rpi0n101
- [x]  Mailing list announcement post @anistark 
- [x]  Website update to display the second keynote speaker. @anistark @SaptakS 

Timeline
Pre 5PM

- [x]  Merge the blog post @vipulgupta2048 @Sc0rpi0n101
- [x]  Draft the social media announcement @rayandas @abhishekmishragithub
- [x]  Merge the website changes @SaptakS @sayanchowdhury 
- [x]  Poster up @noblebatman
- [x]  Email draft @anistark 

Post 5PM

- [x]  Deploy the blog and the website @palnabarun
- [x]  Send the social media announcements out @rayandas @abhishekmishragithub
- [x]  Announce on mailing list @anistark

**Comment by anistark** [comment]
Name: Sebastián Ramírez

Short: Creator of FastAPI, Typer

Bio: 
Sebastián Ramírez (tiangolo) is the creator of FastAPI, Typer, and other open source tools.

He has worked and led teams of developers from Latin America to the Middle East. Always building different types of products and custom solutions involving data processing, distributed systems, and Machine Learning.

FastAPI was included in the last official Python developer survey of 2020, and it was ranked as the 3rd most used Python web framework.

And by different metrics, FastAPI could be considered the Python web framework with the highest growth rate.

FastAPI, Typer, and some of the other open source tools are currently used by many teams of all sizes, from solo developers to many renowned corporations. And these libraries are used for building applications ranging from small data handling tools to complex systems for machine learning, astronomy, and many other fields.

Sebastián was recently part of Explosion, in Germany, the team that created spaCy, a popular open source NLP toolkit.

Currently, Sebastián is dedicating a high percentage of his working time to FastAPI, Typer, and the other open source projects, while also helping a small number of companies and teams as a consultant.

You can learn more about him at his website: https://tiangolo.com

And you can find him on:

* Twitter: https://twitter.com/tiangolo
* GitHub: https://github.com/tiangolo
* LinkedIn: https://www.linkedin.com/in/tiangolo/

**Comment by rayandas** [comment]
Social Media announcement:
```
It's our pleasure to announce Sebastián Ramírez (@) as the second speaker in the keynote lineup of #PyConIndia2021
Sebastián is the creator of FastAPI (@), Typer (@), and other open source tools.
[blog link]
Tickets at: http://bit.ly/pyconindia-tickets
[poster]
```

**Comment by iamaravindsekar** [comment]
Hey folks, the poster can be found in the following url
https://drive.google.com/file/d/1pJKefvbh8_ztLa_kcvy-VAVu2bO_2eEX/view?usp=sharing

The Thumbnails are available in the attached zip file
[SebastianThumbnail.zip](https://github.com/pythonindia/inpycon2021-tasks/files/6576947/SebastianThumbnail.zip)

**Comment by vipulgupta2048** [comment]
Blog Post: https://github.com/pythonindia/inpycon-blog/pull/374

**Comment by anistark** [comment]
@raukadah @RiteshAgrawal  @sayanchowdhury Please review the poster design above.

**Comment by anistark** [comment]
Mail draft: https://pad.riseup.net/p/inpycon21-keynote-2-keep

**Comment by anistark** [comment]
Website and Blog PRs ready to deploy.
@palnabarun @sayanchowdhury
