### ISSUE TITLE
Announce third keynote speaker

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#57]
Info
Scheduled for June 25th, 2021 at 12 PM.

Tasks

- [x]  Social Media announcement post @rayandas
- [x] Thumbnail design @noblebatman 
- [x]  Blog post announcement @Sc0rpi0n101
- [x]  Mailing list announcement post @anistark / @raukadah 
- [x]  Website update to display the second keynote speaker. @anistark @SaptakS 

Timeline
Pre 12PM

- [x]  Merge the blog post @vipulgupta2048 @Sc0rpi0n101
- [x]  Draft the social media announcement @rayandas @abhishekmishragithub
- [x]  Merge the website changes @SaptakS @sayanchowdhury 
- [x]  Poster up @noblebatman
- [x]  Email draft @anistark 

Post 12 PM

- [x]  Deploy the blog and the website @palnabarun
- [x]  Send the social media announcements out @rayandas @abhishekmishragithub
- [x]  Announce on mailing list @anistark

**Comment by raukadah** [comment]
![signal-2021-06-18-124048](https://user-images.githubusercontent.com/47899089/123044327-1fee9d80-d417-11eb-81d6-a469aa3b27d8.jpeg)

**Comment by raukadah** [comment]
*PyCon India Keynote Introduction Blog*


*Dr. AjithKumar B P*

Dr Ajith worked as a senior scientist with Inter University Accelerator Centre, New Delhi from 1985-2021.

He has done his M.Sc and PhD in Nuclear Physics from University of Calicut and M.Sc in Accelerator Physics, from University of Manitoba, Canada. He works mainly in the area of design and development of particle accelerators and instrumentation for associated experiments, including radio-frequency accelerating structures, control and data acquisition systems, digital and radio frequency electronics modules.

Dr. Ajith Kumar initiated the PHOENIX project by designing a parallel port based computer interface for teaching physics and engineering in 2005. His dedicated efforts in developing open science hardware for teaching science, led to the latest development of ExpEYES (https://expeyes.in/).  ExpEYES -An open source science lab, is currently the most affordable  tool for learning science by exploring and experimenting which uses python for data analysis and visualization.

For the past several years he has been involved in promoting Free Software tools in Education. Has been pursuing academic community to include Python in their syllabus and has written a book 'Python for Education'. Dr. Ajith is involved in teacher training programs and has helped thousands of teachers to have hands-on experience with computer interfaced experients and to take their first steps in the world of Free Software and Python. 

Dr Ajith is retired from IUAC in FEB 2021 but the scientist and educator in him will never retire. He has continued his work promoting science education and scientific temper through his new project scischool.in (https://scischool.in/)

**Comment by raukadah** [comment]
@vipulgupta2048 @Sc0rpi0n101 Can we get the blog draft out for review?
@noblebatman Can we get the Keynote poster up?
@rayandas Can we get the tweets draft ready?

**Comment by Sc0rpi0n101** [comment]
Blog draft: https://github.com/pythonindia/inpycon-blog/pull/378

**Comment by rayandas** [comment]
Social media post draft: 
```
It's our pleasure to announce Dr. AjithKumar B P (@) as the third speaker in the keynote lineup of #PyConIndia2021
Dr Ajith worked as a senior scientist with Inter University Accelerator Centre.
[blog link]
Tickets at: http://bit.ly/pyconindia-tickets
[poster]
```

**Comment by iamaravindsekar** [comment]
I have attached the Thumbnail files for the website, Will upload the poster image when the Bio details of the poster is decided.
[Thumbnail-Ajithkumar.zip](https://github.com/pythonindia/inpycon2021-tasks/files/6709252/Thumbnail-Ajithkumar.zip)

**Comment by iamaravindsekar** [comment]
The url to the poster file in the GDrive 
https://drive.google.com/file/d/1km8s8d-szKg8NXSDJIZhtxJWJM-wq5Py/view?usp=sharing
