### ISSUE TITLE
Announce fourth keynote speaker

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2021-tasks#58]
Info
Scheduled for July 1, 2021 at 6 PM.

Tasks

- [x]  Social Media announcement post @rayandas
- [x] Thumbnail design @noblebatman 
- [x]  Blog post announcement @Sc0rpi0n101
- [x]  Mailing list announcement post @anistark / @raukadah 
- [x]  Website update to display the fourth keynote speaker. @anistark @SaptakS 

Timeline
Pre 5PM

- [x]  Merge the blog post @vipulgupta2048 @Sc0rpi0n101
- [x]  Draft the social media announcement @rayandas @abhishekmishragithub
- [x]  Merge the website changes @SaptakS @sayanchowdhury 
- [x]  Poster up @noblebatman
- [x]  Email draft @anistark 

Post 5PM

- [x]  Deploy the blog and the website @palnabarun
- [x]  Send the social media announcements out @rayandas @abhishekmishragithub
- [ ]  Announce on mailing list @anistark

**Comment by RiteshAgrawal** [comment]
![LucianoRamalho2016-2400x3200-2 jpg](https://user-images.githubusercontent.com/6443008/123589970-a46e6100-d807-11eb-95c2-f417dc13cf9b.JPG)

Name: Luciano Ramalho
Short: Author of Fluent Python
Bio:
Luciano Ramalho is the author of Fluent Python (O'Reilly), published
in 9 languages. He's been a professional Python programmer since 1998,
and he just finished writing the Fluent Python, Second Edition,
covering Python 3.9 and 3.10—to be released in Q4, 2021. Ramalho is a
Principal Consultant at ThoughtWorks, and co-founder of Garoa.net.br,
a hackerspace in São Paulo, Brazil.

**Comment by RiteshAgrawal** [comment]
I have added the speaker content.

@vipulgupta2048 @Sc0rpi0n101 Can you please create the blog post?
@noblebatman Can we please have the poster available?
@rayandas Can we have the announcement tweet ready?
@SaptakS Can we have the website changes ready?

**Comment by vipulgupta2048** [comment]
Creating the blog post.

**Comment by iamaravindsekar** [comment]
Added the poster file to the Gdrive, It can be found in the url https://drive.google.com/file/d/1Ggtd2SbxlXCLKmiqAqn4wEageyYThqmk/view?usp=sharing

**Comment by rayandas** [comment]
Social media announcement draft:
```
It's our pleasure to announce Luciano Ramalho (@) as the fourth speaker in the keynote lineup of #PyConIndia2021

As you all know, Luciano is the author of Fluent Python (O'Reilly), published in 9 languages. He's been a professional Python programmer since 1998.
Read more: https://in.pycon.org/blog/2021/keynote-announcement-luciano-ramalho.html

Tickets at: http://bit.ly/pyconindia-tickets

**Comment by iamaravindsekar** [comment]
The url for folder containing Thumbnail...
https://drive.google.com/drive/folders/1qXmPNZCR7mPLXTSjkEEEXrijpLt1Sqkb?usp=sharing

**Comment by RiteshAgrawal** [comment]
@raukadah Email draft: https://pad.riseup.net/p/fourth-speaker-email-tmp

**Comment by raukadah** [comment]
https://mail.python.org/pipermail/inpycon/2021-July/013244.html all done here, closing it.
