### ISSUE TITLE
Create event on FB & LinkedIn for PyCon India 2021

### ISSUE THREAD

**Issue by abhishekmishragithub** [pythonindia/inpycon2021-tasks#9]
### Tasks:

- [x] Create an event on PyCon India Facebook Page
- [x] Create an event on PyCon India LinkedIn Page

**Comment by Thedijje** [comment]
Hi @abhishekmishragithub what's schedule for this? when we are expecting this to be created and what are requirements.
For example 
- Logo
- Description content 
like that?

**Comment by abhishekmishragithub** [comment]
Hey @Thedijje , this will be done once conference schedule will is out. Not urgent now.

**Comment by anistark** [comment]
@rayandas Do we've a Facebook event created yet?

**Comment by rayandas** [comment]
Created.
Facebook: https://www.facebook.com/events/124152263125918
LinkedIn: https://www.linkedin.com/events/6807565082772467712/
